# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: blog.aadunn
author: Alex Dunn
email: alex@aadunn.ca
description:  # this means to ignore newlines until "baseurl:"
  Personal blog for documenting the drab life of Alex Dunn.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.aadunn.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aadunn
linkedin_username: alex@aadunn.ca

# Build settings
markdown: kramdown
sass:
    style: compact
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
