title: blog.aadunn
author: Alex Dunn
email: alex@aadunn.ca
description:  # this means to ignore newlines until "baseurl:"
  Alex Dunn talks about his life and says "homie" too much.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.aadunn.ca" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  aadunn
twitter_username: aadunn_
linkedin_username: alex@aadunn.ca
  
permalink: none

# Build settings
markdown: kramdown
sass:
    style: compact
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
